module.exports = {
    "BCH":{
       "shortName":"BCH",
       "longName":"Bitcoin Cash",
       "network":{
          "p2wpkh":{
             "baseNetwork":"bitcoin",
             "messagePrefix":"\\x18Bitcoin Signed Message:\n",
             "bech32":"bc",
             "bip32":{
                "public":78792518,
                "private":78791436
             },
             "pubKeyHash":0,
             "scriptHash":5,
             "wif":128
          },
          "p2wpkhInP2sh":{
             "baseNetwork":"bitcoin",
             "messagePrefix":"\\x18Bitcoin Signed Message:\n",
             "bech32":"bc",
             "bip32":{
                "public":77429938,
                "private":77428856
             },
             "pubKeyHash":0,
             "scriptHash":5,
             "wif":128
          },
          "p2wsh":{
             "baseNetwork":"bitcoin",
             "messagePrefix":"\\x18Bitcoin Signed Message:\n",
             "bech32":"bc",
             "bip32":{
                "public":44728019,
                "private":44726937
             },
             "pubKeyHash":0,
             "scriptHash":5,
             "wif":128
          },
          "p2wshInP2sh":{
             "baseNetwork":"bitcoin",
             "messagePrefix":"\\x18Bitcoin Signed Message:\n",
             "bech32":"bc",
             "bip32":{
                "public":43365439,
                "private":43364357
             },
             "pubKeyHash":0,
             "scriptHash":5,
             "wif":128
          },
          "p2pkh":{
             "messagePrefix":"\u0018Bitcoin Signed Message:\n",
             "bip32":{
                "public":76067358,
                "private":76066276
             },
             "pubKeyHash":0,
             "scriptHash":5,
             "wif":128,
             "bech32":"bc"
          }
       },
       "coinNumber":145
    },
    "BTC":{
       "shortName":"BTC",
       "longName":"Bitcoin",
       "network":{
          "p2wpkh":{
             "baseNetwork":"bitcoin",
             "messagePrefix":"\\x18Bitcoin Signed Message:\n",
             "bech32":"bc",
             "bip32":{
                "public":78792518,
                "private":78791436
             },
             "pubKeyHash":0,
             "scriptHash":5,
             "wif":128
          },
          "p2wpkhInP2sh":{
             "baseNetwork":"bitcoin",
             "messagePrefix":"\\x18Bitcoin Signed Message:\n",
             "bech32":"bc",
             "bip32":{
                "public":77429938,
                "private":77428856
             },
             "pubKeyHash":0,
             "scriptHash":5,
             "wif":128
          },
          "p2wsh":{
             "baseNetwork":"bitcoin",
             "messagePrefix":"\\x18Bitcoin Signed Message:\n",
             "bech32":"bc",
             "bip32":{
                "public":44728019,
                "private":44726937
             },
             "pubKeyHash":0,
             "scriptHash":5,
             "wif":128
          },
          "p2wshInP2sh":{
             "baseNetwork":"bitcoin",
             "messagePrefix":"\\x18Bitcoin Signed Message:\n",
             "bech32":"bc",
             "bip32":{
                "public":43365439,
                "private":43364357
             },
             "pubKeyHash":0,
             "scriptHash":5,
             "wif":128
          },
          "p2pkh":{
             "messagePrefix":"\u0018Bitcoin Signed Message:\n",
             "bip32":{
                "public":76067358,
                "private":76066276
             },
             "pubKeyHash":0,
             "scriptHash":5,
             "wif":128,
             "bech32":"bc"
          }
       },
       "coinNumber":0
    },
    "DASH":{
       "shortName":"DASH",
       "longName":"Dash",
       "network":{
          "p2pkh":{
             "messagePrefix":"unused",
             "bip32":{
                "public":76067358,
                "private":76066276
             },
             "pubKeyHash":76,
             "scriptHash":16,
             "wif":204
          }
       },
       "coinNumber":5
    },
    "DGB":{
       "shortName":"DGB",
       "longName":"Digibyte",
       "network":{
          "p2wpkh":{
             "baseNetwork":"digibyte",
             "messagePrefix":"x19DigiByte Signed Message:\n",
             "bech32":"dgb",
             "bip32":{
                "public":78792518,
                "private":78791436
             },
             "pubKeyHash":30,
             "scriptHash":63,
             "wif":128
          },
          "p2wpkhInP2sh":{
             "baseNetwork":"digibyte",
             "messagePrefix":"\\x19DigiByte Signed Message:\n",
             "bech32":"dgb",
             "bip32":{
                "public":77429938,
                "private":77428856
             },
             "pubKeyHash":30,
             "scriptHash":63,
             "wif":128
          },
          "p2pkh":{
             "messagePrefix":"\u0019DigiByte Signed Message:\n",
             "bip32":{
                "public":76067358,
                "private":76066276
             },
             "pubKeyHash":30,
             "scriptHash":5,
             "wif":128
          }
       },
       "coinNumber":20
    },
    "DOGE":{
       "shortName":"DOGE",
       "longName":"Dogecoin",
       "network":{
          "p2pkh":{
             "messagePrefix":"\u0019Dogecoin Signed Message:\n",
             "bip32":{
                "public":49990397,
                "private":49988504
             },
             "pubKeyHash":30,
             "scriptHash":22,
             "wif":158
          }
       },
       "coinNumber":3
    },
    "ETH":{
       "shortName":"ETH",
       "longName":"Ethereum",
       "addressType":"ethereum",
       "addressPrefix":"0x",
       "network":{
          "p2pkh":{
             "messagePrefix":"\u0018Bitcoin Signed Message:\n",
             "bip32":{
                "public":76067358,
                "private":76066276
             },
             "pubKeyHash":0,
             "scriptHash":5,
             "wif":128,
             "bech32":"bc"
          }
       },
       "coinNumber":60
    },
    "LTC":{
       "shortName":"LTC",
       "longName":"Litecoin",
       "network":{
          "p2wpkh":{
             "baseNetwork":"litecoin",
             "messagePrefix":"\\x19Litecoin Signed Message:\n",
             "bech32":"ltc",
             "bip32":{
                "public":78792518,
                "private":78791436
             },
             "pubKeyHash":48,
             "scriptHash":50,
             "wif":176
          },
          "p2wpkhInP2sh":{
             "baseNetwork":"litecoin",
             "messagePrefix":"\\x19Litecoin Signed Message:\n",
             "bech32":"ltc",
             "bip32":{
                "public":28471030,
                "private":28469138
             },
             "pubKeyHash":48,
             "scriptHash":50,
             "wif":176
          },
          "p2pkh":{
             "messagePrefix":"\\x19Litecoin Signed Message:\n",
             "bip32":{
                "public":27108450,
                "private":27106558
             },
             "pubKeyHash":48,
             "scriptHash":50,
             "wif":176,
             "bech32":"ltc"
          }
       },
       "coinNumber":2
    },
    "RVN":{
       "shortName":"RVN",
       "longName":"Ravencoin",
       "network":{
          "p2pkh":{
             "messagePrefix":"\u0016Raven Signed Message:\n",
             "bip32":{
                "public":76067358,
                "private":76066276
             },
             "pubKeyHash":60,
             "scriptHash":122,
             "wif":128
          }
       },
       "coinNumber":175
    },
    "SOL":{
       "shortName":"SOL",
       "longName":"Solana",
       "addressType":"solana",
       "network":{
          "p2pkh":{
             "messagePrefix":"\u0018Bitcoin Signed Message:\n",
             "bip32":{
                "public":76067358,
                "private":76066276
             },
             "pubKeyHash":0,
             "scriptHash":5,
             "wif":128,
             "bech32":"bc"
          }
      },
       "coinNumber":501
    },
    "TRX":{
       "shortName":"TRX",
       "longName":"Tron",
       "addressType":"tron",
       "addressPrefix":0x41,
       "network":{
         "p2pkh":{
            "messagePrefix":"\u0018Bitcoin Signed Message:\n",
            "bip32":{
               "public":76067358,
               "private":76066276
            },
            "pubKeyHash":0,
            "scriptHash":5,
            "wif":128,
            "bech32":"bc"
         }
      },
      "coinNumber":195,
    },
    "XLM":{
       "shortName":"XLM",
       "longName":"Stellar",
       "addressType":"stellar",
       "network":{
         "p2pkh":{
            "bip32": {public: 0, private: 0},
            "messagePrefix": '',
            "pubKeyHash": 0,
            "scriptHash": 0,
            "wif": 0,
         }
      },
       "coinNumber":148
    },
    "XRP":{
       "shortName":"XRP",
       "longName":"Ripple",
       "addressType":"ripple",
       "network":{
          "p2pkh":{
             "messagePrefix":"\u0018Bitcoin Signed Message:\n",
             "bip32":{
                "public":76067358,
                "private":76066276
             },
             "pubKeyHash":0,
             "scriptHash":5,
             "wif":128,
             "bech32":"bc"
          }
       },
       "coinNumber":144
    },
    "ZEC":{
       "shortName":"ZEC",
       "longName":"Zcash",
       "network":{
          "p2pkh":{
             "messagePrefix":"\u0018Zcash Signed Message:\n",
             "bip32":{
                "public":76067358,
                "private":76066276
             },
             "pubKeyHash":7352,
             "scriptHash":7357,
             "wif":128
          }
       },
       "coinNumber":133
    }
 }
